# Generated by Django 4.1.5 on 2023-01-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                ("test1", models.IntegerField(primary_key=True, serialize=False)),
                ("test2", models.CharField(max_length=50)),
            ],
        ),
    ]
