# Generated by Django 4.1.5 on 2023-01-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_test_test1_alter_test_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='isDropIn',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
