# Generated by Django 4.1.5 on 2023-01-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_coworkingspace_isdropin"),
    ]

    operations = [
        migrations.AddField(
            model_name="coworkingspace",
            name="isCafe",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coworkingspace",
            name="isEnhancedOptions",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coworkingspace",
            name="isMeetingRoom",
            field=models.IntegerField(),
        ),
    ]
