# Generated by Django 4.1.5 on 2023-01-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_remove_coworkingspace_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coworkingspace", name="endTime", field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="coworkingspace", name="startTime", field=models.TimeField(),
        ),
    ]
