# Generated by Django 4.1.4 on 2023-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_coworkingspace_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='MeetingRoomCapacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='favorite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='options',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='timeFromStation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
