# Generated by Django 4.1.4 on 2023-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_coworkingspace_meetingroomcapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
