# Generated by Django 4.1.4 on 2023-02-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spaceName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
