# Generated by Django 4.1.4 on 2023-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_review_spacename'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='density',
            field=models.FloatField(default=4511.36141),
            preserve_default=False,
        ),
    ]
