# Generated by Django 4.1.4 on 2023-02-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_coworkingspace_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='dropInFee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
