# Generated by Django 4.1.4 on 2023-02-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_coworkingspace_dropinfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='isAria23',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
