# Generated by Django 4.1.4 on 2023-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_coworkingspace_isaria23'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coworkingspace',
            old_name='dropInFee',
            new_name='dropInFeePerDay',
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='dropInFeePerHour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
