# Generated by Django 4.1.5 on 2023-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_rename_dropinfee_coworkingspace_dropinfeeperday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='characteristic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isBook',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isCall',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isCorporateRegistration',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isFreeDrink',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isNappingRoom',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isParking',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isPrinterCopier',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='isReceivingMail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='MeetingRoomCapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='options',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
