# Generated by Django 4.1.4 on 2023-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_coworkingspace_characteristic_coworkingspace_isbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingspace',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
