# Generated by Django 4.1.4 on 2023-05-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_coworkingspace_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coworkingspace',
            old_name='isAria23',
            new_name='isArea23',
        ),
    ]
