# Generated by Django 4.1.4 on 2023-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_rename_isaria23_coworkingspace_isarea23'),
    ]

    operations = [
        migrations.CreateModel(
            name='favoriteTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceID', models.IntegerField()),
                ('spaceID2', models.IntegerField()),
            ],
        ),
    ]
