# Generated by Django 4.1.4 on 2023-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_remove_favoritetable_id_alter_favoritetable_spaceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritetable',
            name='spaceID2',
        ),
        migrations.AddField(
            model_name='favoritetable',
            name='method',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='favoritetable',
            name='recordID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritetable',
            name='userID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='favoritetable',
            name='spaceID',
            field=models.IntegerField(null=True),
        ),
    ]
