# Generated by Django 4.1.5 on 2023-01-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="coWorkingSpace",
            fields=[
                ("spaceID", models.IntegerField(primary_key=True, serialize=False)),
                ("aria", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("station", models.CharField(max_length=50)),
                ("wifi", models.IntegerField()),
                ("isBattery", models.BooleanField()),
                ("isMeetingRoom", models.BooleanField()),
                ("price", models.IntegerField()),
                ("startTime", models.DateTimeField()),
                ("endTime", models.DateTimeField()),
                ("favorite", models.IntegerField()),
                ("jurisdiction", models.CharField(max_length=50)),
            ],
        ),
    ]
